src/objects/IP_Category__c.object
<CustomObject>
    <description>Categories to be displayed when using the lookup on the IP Idea object.</description>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Zone that the category relates to.</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Expert__c.object
<CustomObject>
    <description>Users who are responsible for reviewing ideas in a category.</description>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IP_Category__c.Zone__c</field>
                <operation>equals</operation>
                <valueField>$Source.Zone__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IP_Category__c</referenceTo>
        <relationshipLabel>Experts</relationshipLabel>
        <relationshipName>Experts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Experts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Experts</relationshipLabel>
        <relationshipName>Experts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expert</label>
    <nameField>
        <displayFormat>IPE-{0000}</displayFormat>
        <label>Experts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Idea__c.object
<CustomObject>
    <description>Ideas submitted by Salesforce users.</description>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The category the idea relates to.</description>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IP_Category__c.Available__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>IP_Category__c</referenceTo>
        <relationshipName>IP_Ideas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Point_Threshold_Reached__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean to track is the point threshold of the idea&apos;s zone has ever been reached to prevent performing logic multiple times when it should run once.</description>
        <label>Point Threshold Reached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Zone__c</field>
                <operation>equals</operation>
                <valueField>IP_Status__c.Zone__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IP_Status__c</referenceTo>
        <relationshipLabel>Ideas</relationshipLabel>
        <relationshipName>Ideas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Total Score</label>
        <summarizedField>IP_Vote__c.Points__c</summarizedField>
        <summaryForeignKey>IP_Vote__c.Idea__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Ideas</relationshipLabel>
        <relationshipName>IP_Ideas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Idea</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Status__c.object
<CustomObject>
    <description>Statuses associated to idea platform zones.</description>
    <fields>
        <fullName>Initial_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The status set automatically on a newly created idea.  A zone should only have one initial status.</description>
        <label>Initial Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Threshold_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The status the idea is set to when the point threshold is reached.  A zone should only have one threshold status.</description>
        <label>Threshold Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Used to filter the status list on the idea page.</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Statuses</relationshipLabel>
        <relationshipName>Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Vote__c.object
<CustomObject>
    <description>Holds the vote records used to identify who has voted for an idea and to be rolled up for a point total on the idea.</description>
    <fields>
        <fullName>Idea__c</fullName>
        <description>Idea the vote is associated to.</description>
        <label>Idea</label>
        <referenceTo>IP_Idea__c</referenceTo>
        <relationshipName>IP_Idea_Votes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The point value of the individual vote.  Set by the point value of the zone the parent idea is associated to.</description>
        <label>Points</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upvote__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Boolean to track whether this vote is for or against the idea when calculating the point value.</description>
        <label>Upvote</label>
        <type>Checkbox</type>
    </fields>
    <label>Vote</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Zone__c.object
<CustomObject>
    <fields>
        <fullName>Point_Threshold__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field determines what the threshold is for an idea before it begins the consideration process 
http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Point Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_per_Vote__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field will determine how many points a vote is worth in this zone
http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Points per Vote</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IPIdeaTriggerHelper.cls
public class IPIdeaTriggerHelper {
    public static Map<Id, IP_Zone__c> getInitialStatuses(List<IP_Idea__c> ideas){
        Set<Id> zoneIds = getZoneIds(ideas);
        
        Map<Id, IP_Zone__c> initialStatuses = new Map<Id, IP_Zone__c>([SELECT Id, (SELECT Id FROM Statuses__r WHERE Initial_Status__c = true)
                                                                       FROM IP_Zone__c
                                                                       WHERE Id IN :zoneIds
                                                                      ]);
        
        return initialStatuses;
    }
    
    public static Map<Id, IP_Zone__c> getThresholdStatuses(List<IP_Idea__c> ideas){
        Set<Id> zoneIds = getZoneIds(ideas);
        
        Map<Id, IP_Zone__c> thresholdStatuses = new Map<Id, IP_Zone__c>([SELECT Id, Point_Threshold__c, (SELECT Id FROM Statuses__r WHERE Threshold_Status__c = true)
                                                                         FROM IP_Zone__c
                                                                         WHERE Id IN :zoneIds
                                                                        ]);
        
        return thresholdStatuses;
    }
    
    public static Set<Id> getZoneIds(List<IP_Idea__c> ideas){
        Set<Id> zoneIds = new Set<id>();
        for(IP_Idea__c idea : ideas){
            zoneIds.add(idea.Zone__c);
        }
        
        return zoneIds;
    }
    
    public static void createInitialVote( List<IP_Idea__c> ideaList ){
        
        List<IP_Vote__c> voteList = new List<IP_Vote__c>();
        
        for( IP_Idea__c idea : ideaList ) {
            
            IP_Vote__c vote = new IP_Vote__c(
                Idea__c = idea.Id,
                Points__c = idea.Zone__r.Points_Per_Vote__c,
                Upvote__c = true
            );
            
            voteList.add( vote );
            
        }      
        
        insert voteList; 
        
    }
    
    public static void setIdeaInitialStatus( List<IP_Idea__c> ideaList ){
        Map<Id, IP_Zone__c> initialStatuses = getInitialStatuses( ideaList );
        
        for( IP_Idea__c idea : ideaList ) {
            idea.Status__c = initialStatuses.get(idea.Zone__c).Statuses__r[0].Id;
        }   
    }
    
    public static void evaluateIdeaPointThreshold( List<IP_Idea__c> ideaList ){
        
        List<IP_Idea__c> thresholdReachedIdeaList = getPointThresholdReachedIdeaList( ideaList );
        
        if( !thresholdReachedIdeaList.isEmpty() ){
            
            //Query the list of ideas to get the related category values to use in the chatter post.
            thresholdReachedIdeaList = [
                SELECT
                Id,
                Category__c,
                Category__r.Post_to_Chatter_Message__c,
                Category__r.Post_to_Chatter_as_User__c
                FROM IP_Idea__c
                WHERE Id IN :thresholdReachedIdeaList
            ];
            
            //Subscribes experts to the ideas and then posts to chatter to send them a notification.
            subscribeExpertsToIdea( thresholdReachedIdeaList );
            createPointThresholdPost( thresholdReachedIdeaList );
        }
    }
    
    public static List<IP_Idea__c> getPointThresholdReachedIdeaList( List<IP_Idea__c> ideaList ){
        List<IP_Idea__c> thresholdReachedIdeaList = new List<IP_Idea__c>();
        Map<Id, IP_Zone__c> thresholdStatuses = getThresholdStatuses( ideaList );
        
        for( IP_Idea__c idea : ideaList ) {
            Decimal pointThreshold = thresholdStatuses.get( idea.Zone__c ).Point_Threshold__c;
            
            if( idea.Total_Score__c >= pointThreshold && !idea.Point_Threshold_Reached__c ) {
                idea.Point_Threshold_Reached__c = true;
                idea.Status__c = thresholdStatuses.get( idea.Zone__c ).Statuses__r[0].Id;
                thresholdReachedIdeaList.add( idea );
            }
        }
        return thresholdReachedIdeaList;
    }
    
    public static void subscribeExpertsToIdea( List<IP_Idea__c> ideaList ){
        Map<Id,List<Id>> ideaToExpertsMap = new Map<Id,List<Id>>();
        Set<Id> categoryIdSet = new Set<Id>();
        
        for( IP_Idea__c idea : ideaList ){
            categoryIdSet.add( idea.Category__c );
        }
        Map<Id,List<Id>> categoryToExpertsMap = getCategoryToExpertsMap( categoryIdSet );
        
        for( IP_Idea__c idea : ideaList ){
            if( categoryToExpertsMap.get( idea.Category__c ) != null ){
                ideaToExpertsMap.put( idea.Id, categoryToExpertsMap.get( idea.Category__c ) );
            }
        }
        
        if( !ideaToExpertsMap.isEmpty() ){
            IPChatterUtils.addFollowersToRecords( ideaToExpertsMap );
        }
    }
    
    public static void createPointThresholdPost( List<IP_Idea__c> ideaList ){
        Map<Id, String> recordIdToBodyMap = new Map<Id, String>();
        List<FeedItem> feedItemList = new List<FeedItem>();
        
        for( IP_Idea__c idea : ideaList ){
            String body;
            String chatterMessage = idea.Category__r.Post_to_Chatter_Message__c;
            if( String.isBlank( chatterMessage ) ){
                body = 'Point Threshold Reached';
            }else{
                body = chatterMessage;
            }
            feedItemList.add( IPChatterUtils.createFeedItem( idea.Id, body, idea.Category__r.Post_to_Chatter_As_User__c ) );
        }
        
        insert feedItemList;
        
    }
    
    public static Map<Id,List<Id>> getCategoryToExpertsMap( Set<Id> categoryIdSet ) {
        Map<Id,List<Id>> categoryToExpertsMap = new Map<Id,List<Id>>();
        
        List<IP_Expert__c> expertList = [
            SELECT 
            Id,
            User__c,
            Category__c
            FROM IP_Expert__c 
            WHERE Category__c = :categoryIdSet
        ];
        
        for( Id cId : categoryIdSet ){
            for( IP_Expert__c expert : expertList ){
                if( expert.Category__c == cId ){
                    if( categoryToExpertsMap.get( cId ) == null ){
                        categoryToExpertsMap.put( cId, new List<Id>{expert.User__c} );
                    }else{
                        List<Id> tempIdList = categoryToExpertsMap.get( cId );
                        tempIdList.add( expert.User__c );
                        categoryToExpertsMap.put( cId, tempIdList );
                    }
                }
            }
        }     
        
        return categoryToExpertsMap;
    }
    
}