src/objects/IP_Category__c.object
<CustomObject>
    <description>Categories to be displayed when using the lookup on the IP Idea object.</description>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Zone that the category relates to.</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Status__c.object
<CustomObject>
    <description>Statuses associated to idea platform zones.</description>
    <fields>
        <fullName>Display_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Display Order is used to sort the list of status in a particular order</description>
        <inlineHelpText>Display Order is used to sort the list of status in a particular order</inlineHelpText>
        <label>Display Order</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Initial_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The status set automatically on a newly created idea.  A zone should only have one initial status.</description>
        <label>Initial Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lock_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Status that represents the end of the lifecycle of an idea.  Many status can be lock status.</description>
        <label>Lock Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Threshold_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The status the idea is set to when the point threshold is reached.  A zone should only have one threshold status.</description>
        <label>Threshold Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Used to filter the status list on the idea page.</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Statuses</relationshipLabel>
        <relationshipName>Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Zone__c.object
<CustomObject>
    <fields>
        <fullName>Point_Threshold__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field determines what the threshold is for an idea before it begins the consideration process 
http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Point Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_per_Vote__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field will determine how many points a vote is worth in this zone
http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Points per Vote</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IPIdeaSeedUtility.cls
public class IPIdeaSeedUtility {
	
	public static void createSampleData() {
		
		IP_Zone__c zone = createZone();
		
		createStatuses( zone.Id );
		
		createCategory( zone.Id, 'Lightning' );
		createCategory( zone.Id, 'Process Builder' );
										
	}	
	
	private static IP_Zone__c createZone() {
		
		IP_Zone__c zone = new IP_Zone__c(
			Name = 'Sample Community',
			Points_Per_Vote__c = 10,
			Point_Threshold__c = 100
		);
		
		insert zone;
		
		return zone;
		
	}
	
	private static void createStatuses( Id zoneId ) {
		
		List<IP_Status__c> statusList = new List<IP_Status__c>();
		
		IP_Status__c initialStatus = new IP_Status__c(
			Name = 'New',
			Zone__c = zoneId,
			Initial_Status__c = true,
			Display_Order__c = 10
		);		
		
		IP_Status__c underReviewStatus = new IP_Status__c(
			Name = 'Under Review',
			Zone__c = zoneId,
			Threshold_Status__c = true,
			Display_Order__c = 20
		);	
		
		IP_Status__c deliveredStatus = new IP_Status__c(
			Name = 'Delivered',
			Zone__c = zoneId,
			Lock_Status__c = true,
			Display_Order__c = 30
		);	
		
		statusList.add( initialStatus );
		statusList.add( underReviewStatus );
		statusList.add( deliveredStatus );
		
		insert statusList;
		
	}
	
	private static IP_Category__c createCategory( Id zoneId, String categoryName ) {
		
		IP_Category__c category = new IP_Category__c(
			Name = categoryName,
			Zone__c = zoneId			 						
		);
		
		insert category;
		
		return category;
		
	}
	
}