src/objects/IP_Category__c.object
<CustomObject>
    <description>Categories to be displayed when using the lookup on the IP Idea object.</description>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Zone that the category relates to.</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Expert__c.object
<CustomObject>
    <description>Users who are responsible for reviewing ideas in a category.</description>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IP_Category__c.Zone__c</field>
                <operation>equals</operation>
                <valueField>$Source.Zone__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IP_Category__c</referenceTo>
        <relationshipLabel>Experts</relationshipLabel>
        <relationshipName>Experts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Experts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Experts</relationshipLabel>
        <relationshipName>Experts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expert</label>
    <nameField>
        <displayFormat>IPE-{0000}</displayFormat>
        <label>Experts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Idea__c.object
<CustomObject>
    <description>Ideas submitted by Salesforce users.</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The category the idea relates to.</description>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IP_Category__c.Available__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>IP_Category__c</referenceTo>
        <relationshipName>IP_Ideas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Total Score</label>
        <summarizedField>IP_Vote__c.Points__c</summarizedField>
        <summaryForeignKey>IP_Vote__c.Idea__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Ideas</relationshipLabel>
        <relationshipName>IP_Ideas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Idea</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Status__c.object
<CustomObject>
    <description>Statuses associated to idea platform zones.</description>
    <fields>
        <fullName>Display_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Display Order is used to sort the list of status in a particular order</description>
        <inlineHelpText>Display Order is used to sort the list of status in a particular order</inlineHelpText>
        <label>Display Order</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Initial_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The status set automatically on a newly created idea.  A zone should only have one initial status.</description>
        <label>Initial Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Threshold_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The status the idea is set to when the point threshold is reached.  A zone should only have one threshold status.</description>
        <label>Threshold Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Used to filter the status list on the idea page.</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Statuses</relationshipLabel>
        <relationshipName>Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Vote__c.object
<CustomObject>
    <description>Holds the vote records used to identify who has voted for an idea and to be rolled up for a point total on the idea.</description>
    <fields>
        <fullName>Idea__c</fullName>
        <description>Idea the vote is associated to.</description>
        <label>Idea</label>
        <referenceTo>IP_Idea__c</referenceTo>
        <relationshipName>IP_Idea_Votes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Upvote__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Boolean to track whether this vote is for or against the idea when calculating the point value.</description>
        <label>Upvote</label>
        <type>Checkbox</type>
    </fields>
    <label>Vote</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Zone__c.object
<CustomObject>
    <fields>
        <fullName>Point_Threshold__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field determines what the threshold is for an idea before it begins the consideration process 
http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Point Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_per_Vote__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field will determine how many points a vote is worth in this zone
http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Points per Vote</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IPIdeaControllerTest.cls
@isTest
public class IPIdeaControllerTest {

    @isTest
    static void test_getUserId() {
        Test.startTest();

        String userId = IPIdeaController.getUserId();

        Test.stopTest();

        system.assertEquals((String) UserInfo.getUserId(), userId);
    }

    @isTest
    static void test_getIdeasByZoneId_noFilterOrSort(){

        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Idea__c idea = createIdea(zone.Id);
        IP_Idea__c idea2 = createIdea(zone.Id);

        Map<Id, IP_Idea__c> ideaMap = new Map<Id, IP_Idea__c>();
        ideaMap.put(idea.Id, idea);
        ideaMap.put(idea2.Id, idea2);

        Test.startTest();

        List<IP_Idea__c> retrievedIdeas = IPIdeaController.getIdeasByZoneId( zone.Id, '', '' );

        Test.stopTest();

        System.assert(retrievedIdeas.size() == 2);
        for(IP_Idea__c i : retrievedIdeas){
            System.assert(ideaMap.containsKey(i.Id));
        }
    }

    @isTest
    //In addition to testing the filter code, this also tests that the workflow rule is updating the status correctly when the point threshold is reached.
    static void test_getIdeasByZoneId_filter(){
        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Status__c thresholdStatus = createThresholdStatus(zone.Id);
        IP_Idea__c idea = createIdea(zone.Id);
        IP_Idea__c idea2 = createIdea(zone.Id);
        IP_Vote__c vote = createVote(idea2.Id);
        IP_Vote__c vote2 = createVote(idea2.Id);

        Test.startTest();

        List<IP_Idea__c> retrievedIdeas = IPIdeaController.getIdeasByZoneId( zone.Id, 'Threshold', '' );

        Test.stopTest();

        System.assert(retrievedIdeas.size() == 1);
        for(IP_Idea__c i : retrievedIdeas){
            System.assertEquals(i.Id, idea2.Id);
        }
    }

    @isTest
    static void test_getIdeasByZoneId_sortPopular(){
        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Status__c thresholdStatus = createThresholdStatus(zone.Id);
        IP_Idea__c idea = createIdea(zone.Id);
        IP_Idea__c idea2 = createIdea(zone.Id);
        IP_Vote__c vote = createVote(idea2.Id, false);

        Test.startTest();

        List<IP_Idea__c> retrievedIdeas = IPIdeaController.getIdeasByZoneId( zone.Id, '', 'Popular' );

        Test.stopTest();

        System.assertEquals(retrievedIdeas[0].Id, idea2.Id);
        System.assertEquals(retrievedIdeas[1].Id, idea.Id);
    }

    @isTest
    static void test_getIdeasByZoneId_sortTrending(){
        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Status__c thresholdStatus = createThresholdStatus(zone.Id);
        IP_Idea__c idea = createIdea(zone.Id);
        IP_Idea__c idea2 = createIdea(zone.Id);
        IP_Vote__c vote = createVote(idea2.Id, false);

        Test.startTest();

        List<IP_Idea__c> retrievedIdeas = IPIdeaController.getIdeasByZoneId( zone.Id, '', 'Trending' );

        Test.stopTest();

        System.assertEquals(retrievedIdeas[0].Id, idea.Id);
        System.assertEquals(retrievedIdeas[1].Id, idea2.Id);
    }

    @isTest
    static void test_getIdeasByZoneId_sortRecent(){
        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Status__c thresholdStatus = createThresholdStatus(zone.Id);
        IP_Category__c category = createCategory( zone.Id );
        IP_Idea__c idea = createIdea(zone.Id);
        IP_Idea__c idea2 = new IP_Idea__c(
            Title__c = 'Title',
            Body__c = 'Body',
            Category__c = category.Id,
            Zone__c = zone.Id
        );

        insert idea2;

        Test.startTest();

        List<IP_Idea__c> retrievedIdeas = IPIdeaController.getIdeasByZoneId( zone.Id, '', 'Recent' );

        Test.stopTest();

        System.assertEquals(retrievedIdeas[0].Id, idea.Id);
        System.assertEquals(retrievedIdeas[1].Id, idea2.Id);
    }

    @isTest
    static void test_hasVotedOnIdea_true(){
        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Status__c thresholdStatus = createThresholdStatus(zone.Id);
        IP_Idea__c idea = createIdea(zone.Id);
        IP_Vote__c vote = createVote(idea.Id, false);

        Test.startTest();

        Boolean voted = IPIdeaController.hasVotedOnIdea( idea.Id );

        Test.stopTest();

        System.assert(voted);
    }

    @isTest
    static void test_hasVotedOnIdea_false(){
        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Status__c thresholdStatus = createThresholdStatus(zone.Id);
        IP_Idea__c idea = createIdea(zone.Id);
        IP_Vote__c vote = [SELECT Id FROM IP_Vote__c WHERE Idea__c = :idea.Id];

        Delete vote;

        Test.startTest();

        Boolean voted = IPIdeaController.hasVotedOnIdea( idea.Id );

        Test.stopTest();

        System.assert(!voted);
    }

    @isTest
    static void test_getIdeaVoteList(){
        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Status__c thresholdStatus = createThresholdStatus(zone.Id);
        IP_Idea__c idea = createIdea(zone.Id);
        IP_Vote__c vote = [SELECT Id FROM IP_Vote__c WHERE Idea__c = :idea.Id];
        IP_Vote__c vote2 = createVote(idea.Id, false);
        IP_Vote__c vote3 = createVote(idea.Id, false);

        Map<Id, IP_Vote__c> voteMap = new Map<Id, IP_Vote__c>();
        voteMap.put(vote.Id, vote);
        voteMap.put(vote2.Id, vote2);
        voteMap.put(vote3.Id, vote3);

        Test.startTest();

        List<IP_Vote__c> voteList = IPIdeaController.getIdeaVoteList( idea.Id );

        Test.stopTest();

        for(IP_Vote__c v : voteList){
            System.assert(voteMap.containsKey(v.Id));
        }
    }

    @isTest
    static void test_voteForIdea(){
        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Status__c thresholdStatus = createThresholdStatus(zone.Id);
        IP_Idea__c idea = createIdea(zone.Id);

        Test.startTest();

        IPIdeaController.voteForIdea( idea.Id, true );

        Test.stopTest();

        List<IP_Vote__c> voteList = [SELECT Id FROM IP_Vote__c WHERE Idea__c = :idea.Id];

        System.assert(voteList.size() == 2);
    }

    @isTest
    static void test_saveIdea_newIdea(){

        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Status__c thresholdStatus = createThresholdStatus(zone.Id);
        IP_Category__c category = createCategory( zone.Id );
        IP_Idea__c idea = new IP_Idea__c(
            Title__c = 'Title',
            Body__c = 'Body',
            Category__c = category.Id
        );

        Test.startTest();

        IP_Idea__c newIdea = IPIdeaController.saveIdea( zone.Id, idea);

        Test.stopTest();

        newIdea = [SELECT Id, Total_Score__c FROM IP_Idea__c WHERE Id = :newIdea.Id];

        System.assert(newIdea.Total_Score__c == zone.Points_Per_Vote__c);
    }

    @isTest
    static void test_isExpert_true(){
        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Idea__c idea = createIdea(zone.Id);
        IP_Category__c category = [SELECT Id, Zone__c FROM IP_Category__c WHERE Id = :idea.Category__c];
        IP_Expert__c expert = createExpert(zone.Id, category.Id);

        Test.startTest();

        Boolean isZoneExpert = IPIdeaController.isExpert( idea.Id );

        Test.stopTest();

        System.assert(isZoneExpert);
    }

    @isTest
    static void test_isZoneExpert_false(){
        IP_Zone__c zone = createZone();
        IP_Status__c initialStatus = createInitialStatus(zone.Id);
        IP_Idea__c idea = createIdea(zone.Id);
        IP_Category__c category = [SELECT Id, Zone__c FROM IP_Category__c WHERE Id = :idea.Category__c];

        Test.startTest();

        Boolean isZoneExpert = IPIdeaController.isExpert( idea.Id );

        Test.stopTest();

        System.assert(!isZoneExpert);
    }

    private static IP_Zone__c createZone(){
        IP_Zone__c zone = new IP_Zone__c (
            Name = 'Test Zone',
            Points_Per_Vote__c = 10,
            Point_Threshold__c = 15
        );

        insert zone;
        return zone;
    }

    private static IP_Idea__c createIdea(Id zoneId){

        IP_Category__c category = createCategory( zoneId );

        IP_Idea__c idea = new IP_Idea__c(
            Title__c = 'Title',
            Body__c = 'Body',
            Category__c = category.Id,
            Zone__c = zoneId
        );

        insert idea;
        return idea;
    }

    private static IP_Vote__c createVote(Id ideaId){
        IP_Vote__c vote = createVote(ideaId, true);
        return vote;
    }

    private static IP_Vote__c createVote(Id ideaId,Boolean upvote){
        IP_Vote__c vote = new IP_Vote__c(
            Idea__c = ideaId,
            Upvote__c = upvote
        );

        insert vote;
        return vote;
    }

    private static IP_Category__c createCategory( Id zoneId ) {

        IP_Category__c category = new IP_Category__c(
            Zone__c = zoneId,
            Name = 'Information Technology'
        );

        insert category;
        return category;

    }

    private static IP_Status__c createInitialStatus( Id zoneId ) {

        IP_Status__c status = new IP_Status__c(
            Zone__c = zoneId,
            Name = 'Initial',
            Initial_Status__c = true,
            Display_Order__c = 1
        );

        insert status;
        return status;

    }

    private static IP_Status__c createThresholdStatus( Id zoneId ) {

        IP_Status__c status = new IP_Status__c(
            Zone__c = zoneId,
            Name = 'Threshold',
            Threshold_Status__c = true,
            Display_Order__c = 2
        );

        insert status;
        return status;

    }

    private static IP_Expert__c createExpert( Id zoneId, Id categoryId ){
        IP_Expert__c expert = new IP_Expert__c(
        	Zone__c = zoneId,
            User__c = UserInfo.getUserId(),
            Category__c = categoryId
        );

        insert expert;
        return expert;
    }

}