src/objects/IP_Category__c.object
<CustomObject>
    <description>Categories to be displayed when using the lookup on the IP Idea object.</description>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if the category should be displayed when users search for categories for ideas.  This allows categories to remain for reporting without cluttering the lookup with unused values.</description>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Zone that the category relates to.</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Expert__c.object
<CustomObject>
    <description>Users who are responsible for reviewing ideas in a category.</description>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IP_Category__c.Zone__c</field>
                <operation>equals</operation>
                <valueField>$Source.Zone__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IP_Category__c</referenceTo>
        <relationshipLabel>Experts</relationshipLabel>
        <relationshipName>Experts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Experts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Experts</relationshipLabel>
        <relationshipName>Experts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expert</label>
    <nameField>
        <displayFormat>IPE-{0000}</displayFormat>
        <label>Experts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Idea__c.object
<CustomObject>
    <description>Ideas submitted by Salesforce users.</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The category the idea relates to.</description>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IP_Category__c.Available__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>IP_Category__c</referenceTo>
        <relationshipName>IP_Ideas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Zone__c</field>
                <operation>equals</operation>
                <valueField>IP_Status__c.Zone__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IP_Status__c</referenceTo>
        <relationshipLabel>Ideas</relationshipLabel>
        <relationshipName>Ideas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Total Score</label>
        <summarizedField>IP_Vote__c.Points__c</summarizedField>
        <summaryForeignKey>IP_Vote__c.Idea__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Votes__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Total Votes</label>
        <summaryForeignKey>IP_Vote__c.Idea__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>http://jira.fruit.com/browse/SFDC-1129</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Ideas</relationshipLabel>
        <relationshipName>IP_Ideas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Idea</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Status__c.object
<CustomObject>
    <description>Statuses associated to idea platform zones.</description>
    <fields>
        <fullName>Display_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Display Order is used to sort the list of status in a particular order</description>
        <inlineHelpText>Display Order is used to sort the list of status in a particular order</inlineHelpText>
        <label>Display Order</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Lock_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Status that represents the end of the lifecycle of an idea.  Many status can be lock status.</description>
        <label>Lock Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Used to filter the status list on the idea page.</description>
        <label>Zone</label>
        <referenceTo>IP_Zone__c</referenceTo>
        <relationshipLabel>Statuses</relationshipLabel>
        <relationshipName>Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Vote__c.object
<CustomObject>
    <description>Holds the vote records used to identify who has voted for an idea and to be rolled up for a point total on the idea.</description>
    <fields>
        <fullName>Idea__c</fullName>
        <description>Idea the vote is associated to.</description>
        <label>Idea</label>
        <referenceTo>IP_Idea__c</referenceTo>
        <relationshipName>IP_Idea_Votes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Upvote__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Boolean to track whether this vote is for or against the idea when calculating the point value.</description>
        <label>Upvote</label>
        <type>Checkbox</type>
    </fields>
    <label>Vote</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IP_Zone__c.object
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IPIdeaController.cls
public with sharing class IPIdeaController { 
    
    public IPIdeaController( ApexPages.StandardController controller ) {

    }  
    
    public PageReference redirectToLightning() {
        
        String ideaId = ApexPages.currentPage().getParameters().get('id');
        
        PageReference reference = new PageReference( '/one/one.app#/sObject/' + ideaId + '/view' );
        
        reference.setRedirect( true );
        
        return reference;       
        
    }
    
    @AuraEnabled
    public static String getUserId() {
        return UserInfo.getUserId();
    }

    @AuraEnabled
    public static List<IP_Idea__c > getIdeasByZoneId( Id zoneId, String filterBy, String sortBy ) {
        
        String baseQuery = 'SELECT Id, Body__c, Category__r.Name, Zone__c, CreatedDate, CreatedBy.Id, CreatedBy.Name, CreatedBy.FullPhotoUrl, CreatedBy.SmallPhotoUrl, LastViewedDate, Status__r.Name, Title__c, Total_Votes__c, Total_Score__c FROM IP_Idea__c WHERE Zone__c = :zoneId';

        Boolean hasFilter = ( String.isNotBlank( filterBy ) && filterBy != 'All' );
        Boolean hasSort = ( String.isNotBlank( sortBy ) && sortBy != 'All' );

        if( hasFilter ) {

            filterBy = String.escapeSingleQuotes( filterBy );
            String tempFilterBy = '%' + filterBy + '%';
            String filterQuery = ' AND ( Status__r.Name = :filterBy OR Category__r.Name LIKE :tempFilterBy )';

            baseQuery += filterQuery;

        }

        if( hasSort ) {

            // translate option to correct field on Idea object
            if( sortBy == 'Popular' ) {
                sortBy = 'Total_Votes__c';
            }
            else if( sortBy == 'New' ) {
                sortBy = 'CreatedDate';
            }
            else if( sortBy == 'Recent Activity' ) {
                sortBy = 'LastModifiedDate';
            }
            else {
                sortBy = null;
            }
            
            if(String.isNotBlank( sortBy )){
                baseQuery += ' ORDER BY ' + sortBy + ' DESC';
            }

        } else {
            baseQuery += ' ORDER BY CreatedDate DESC';
        }
        
        List<IP_Idea__c> ideaList = Database.query( baseQuery );
        
        return ideaList;

    }

    @AuraEnabled
    public static Boolean isExpert( String ideaId ) {        
        
        List<IP_Expert__c> expertList = getIdeaExperts( ideaId );
        
        Id currentUserId = getUserId();

        for( IP_Expert__c expert : expertList ) {
            if( expert.User__c == currentUserId ) {
                return true;
            }
        }

        return false;
        
    }
    
    @AuraEnabled
    public static List<IP_Expert__c> getIdeaExperts( String ideaId ) {
        
        IP_Idea__c idea = getIdea( ideaId );
        
        List<IP_Expert__c> expertList = [
            SELECT 
                Id,
                User__c,
                User__r.Email,
                User__r.Name,
                User__r.SmallPhotoUrl
            FROM 
                IP_Expert__c 
            WHERE  
                Zone__c = :idea.Zone__c
                AND
                Category__c = :idea.Category__c
        ];
        
        return expertList;
        
    }

    @AuraEnabled
    public static Boolean hasVotedOnIdea( String ideaId ) {

        String userId = getUserId();

        Integer count = [SELECT count() FROM IP_Vote__c WHERE CreatedById = :userId AND Idea__c = :ideaId];

        if( count > 0 ) {
            return true;
        }

        return false;

    }
    
    @AuraEnabled
    public static Boolean hasLockStatus( String ideaId ) {

        String userId = getUserId();

        IP_Idea__c idea = getIdea(ideaId);

        if(idea.Status__r.Lock_Status__c){
            return true;
        }
        
        return false;

    }
    
    @AuraEnabled
    public static Boolean isIdeaAdmin( ) {

        String userId = getUserId();
        
        try{
        	PermissionSetAssignment psa = [ SELECT Id
                                          	FROM PermissionSetAssignment
                                          	WHERE AssigneeId = :userId
                                          		AND PermissionSet.Name = 'IP_Idea_Admin'
                                          ];
            return true;
        }catch( Exception e ){
            return false;
        }

    }

    @AuraEnabled
    public static List<IP_Vote__c> getIdeaVoteList( String ideaId ) {

        List<IP_Vote__c> voteList = [
            SELECT
                Id,
                CreatedBy.Name,
                CreatedBy.SmallPhotoUrl,
                Upvote__c
            FROM
                IP_Vote__c
            WHERE
                Idea__c = :ideaId
        ];

        return voteList;

    }

    @AuraEnabled
    public static void voteForIdea( String ideaId, Boolean direction ) {

        IP_Vote__c vote = new IP_Vote__c();

        vote.Idea__c = ideaId;
        vote.Upvote__c = direction;

        insert vote;

    }

    @AuraEnabled
    public static IP_Idea__c getIdea( String ideaId ) {
        
        IP_Idea__c idea = [
            SELECT 
                Id, 
                Body__c, 
                Category__c,
                Category__r.Name,
                Zone__c,
                Zone__r.Name, 
                CreatedDate, 
                CreatedBy.Id, 
                CreatedBy.Name, 
                CreatedBy.FullPhotoUrl, 
                CreatedBy.SmallPhotoUrl, 
                LastViewedDate, 
                Status__r.Name,
                Status__r.Lock_Status__c,
                Title__c, 
                Total_Votes__c, 
                Total_Score__c 
            FROM
                IP_Idea__c 
            WHERE
                Id = :ideaId
        ];
        
        return idea;
        
    }
    
    @AuraEnabled
    public static IP_Idea__c saveIdea( String zoneId, IP_Idea__c idea ) {

        
        // Determine if the record is an existing idea to determine if an initial vote needs to be created
        Boolean isNewIdea = false;
        if( String.isBlank( idea.Id ) ){
            isNewIdea = true;
        }
        
        if( isNewIdea ){
            // set zone id
            idea.Zone__c = zoneId;
        }

        upsert idea;
        return idea;
    }

    @AuraEnabled
    public static IP_Zone__c getZone( String zoneId ) {
        return [
            SELECT
                Id,
                Name,
                OwnerId,
                (SELECT Name FROM Statuses__r ORDER BY Display_Order__c asc),
                (SELECT Name FROM Categories__r WHERE Available__c = true)
            FROM
                IP_Zone__c 
            WHERE
                Id = :zoneId
        ];
    }
    
}